version: 2
updates:
  - package-ecosystem: npm
    target-branch: main
    directory: /lambdas/get-addresses
    schedule:
      interval: weekly
    labels:
      - dependabot
    commit-message:
      prefix: DEP
    ignore:
      - dependency-name: node
        versions: [17.x, 18.x]
    groups:
      aws:
        patterns:
          - @aws-*
      eslint:
        patterns:
          - eslint
          - eslint-*
          - @typescript-eslint/*
  - package-ecosystem: github-actions
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependabot
    commit-message:
      prefix: DEP
  - package-ecosystem: gradle
    target-branch: main
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependabot
    commit-message:
      prefix: DEP
