version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/lambdas/get-addresses'
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
    - dependabot
    ignore:
      - dependency-name: "node"
        versions: ["17.x","18.x"]
    commit-message:
      prefix: BAU
    groups:
      aws:
        patterns:
          - "@aws-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: main
    labels:
    - dependabot
  - package-ecosystem: "gradle"
    directory: "/"
    commit-message:
      prefix: BAU
    schedule:
      interval: "weekly"
    target-branch: main
    labels:
    - dependabot
