@startuml
'https://plantuml.com/sequence-diagram

autonumber
skinparam backgroundColor #ffffff

'actor User
box "Relying Party" #d0ffee
participant Core as core
end box

box "Credential Issuer"
participant Frontend as fe
participant API as api
database Datastore as db

box "Third Party" #e4ffde
participant "Postcode Lookup" as pcl
end box
== Oauth start ==

core -[#green]> fe : /authorize\n{ jwt }
activate fe

fe -> api: POST /session\n{ OAuth as json }
activate api
api -> api: validate JWT
api -> api: create session
api -> db: write session
return session-id

== Postcode start ==

fe-[#blue]>fe: display post code page

fe -> api: GET /postcode-lookup
activate api
api->pcl: /postcode-lookup
api<--pcl: addresses
return addresses

fe-[#blue]>fe: display addresses

fe->api: POST /address
activate api

api -> api: create authorization_code
api -> db: write address, authorization_code
return 201

fe -> api: POST /authorization
activate api
api -> api: get authorization_code from session-id
db -> api: read authorization_code
api -> fe: authorization_code
destroy api

core <[#green]- fe: /callback\n(authorization_code)
destroy fe
== Oauth return ==



core -[#green]> api: /token (authorization_code)
activate api
api -> api: create token
api -> db: write token
return token
core -[#green]> api: /credential/issue (token)
activate api
api -> api: use AuthenticationResult in verifiable-credential
return verifiable-credential


destroy api
@enduml