name: Check PR

on:
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  code-quality:
    name: Code quality
    uses: ./.github/workflows/code-quality.yml

  unit-tests-ts:
    name: Unit tests
    uses: ./.github/workflows/run-unit-tests-ts.yml
    with:
      coverage-report: true

  unit-tests-java:
    name: Unit tests
    uses: ./.github/workflows/run-unit-tests-java.yml

  deploy:
    name: Preview
    uses: ./.github/workflows/deploy-branch.yml
    permissions:
      id-token: write
      contents: read

  pact-tests:
    name: Run Pact tests
    uses: ./.github/workflows/run-pact-tests.yml
    secrets:
      pact-broker-host: ${{ secrets.PACT_BROKER_HOST }}
      pact-broker-username: ${{ secrets.PACT_BROKER_USERNAME }}
      pact-broker-password: ${{ secrets.PACT_BROKER_PASSWORD }}

  integration-tests:
    name: Run tests
    needs: deploy
    uses: ./.github/workflows/run-integration-tests.yml
    permissions:
      id-token: write
      contents: read
    with:
      aws-region: ${{ needs.deploy.outputs.aws-region }}
      stack-name: ${{ needs.deploy.outputs.stack-name }}
      stack-outputs: ${{ needs.deploy.outputs.stack-outputs }}
    secrets:
      aws_role_arn: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
      api-gateway-api-key: ${{ secrets.APIGW_API_KEY }}
      ipv-core-stub-basic-auth-user: ${{ secrets.IPV_CORE_STUB_BASIC_AUTH_USER }}
      ipv-core-stub-basic-auth-pwd: ${{ secrets.IPV_CORE_STUB_BASIC_AUTH_PASSWORD }}
