name: Preview

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      stack-name:
        description: The deployed stack name
        value: ${{ jobs.deploy.outputs.stack-name }}
      aws-region:
        description: The region in which the stack was deployed
        value: ${{ jobs.deploy.outputs.aws-region }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build SAM app
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
          cache: gradle

      - name: Build SAM application
        uses: govuk-one-login/github-actions/sam/build-application@cd7d35dde348251237efbbaee5345e95adef0321
        id: build
        with:
          template: infrastructure/lambda/template.yaml
          artifact-name: address-api
          cache-key: address-api
          pull-repository: false

  deploy:
    name: Deploy stack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build
    concurrency:
      group: deploy-development-${{ github.head_ref || github.ref_name }}
    environment:
      name: development
      url: ${{ steps.deploy.outputs.stack-url }}
    outputs:
      aws-region: ${{ steps.deploy.outputs.aws-region }}
      stack-name: ${{ steps.deploy.outputs.stack-name }}
    steps:
      - name: Deploy stack
        uses: govuk-one-login/github-actions/sam/deploy-stack@cd7d35dde348251237efbbaee5345e95adef0321
        id: deploy
        with:
          sam-deployment-bucket: ${{ vars.DEPLOYMENT_ARTIFACTS_BUCKET }}
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          stack-name-prefix: preview-address-api
          s3-prefix: preview
          pull-repository: true
          delete-failed-stack: true
          artifact-path: .aws-sam/build
          artifact-name: ${{ needs.build.outputs.artifact-name }}
          tags: |
            cri:component=ipv-cri-address-api
            cri:stack-type=preview
            cri:application=Orange
            cri:deployment-source=github-actions
          parameters: |
            Environment=dev
            CodeSigningEnabled=false
