name: Pre-merge integration test
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  deploy:
    name: pre-merge-integration-tests
    runs-on: ubuntu-latest
    environment: di-ipv-cri-dev
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: dev
      STACK_NAME_PREFIX: pre-merge-integration
      SECRET_PREFIX: pre-merge-test
    permissions:
      id-token: write
      contents: write
      packages: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          version: 1.74.0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4.2

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM build
        run: sam build -t infrastructure/lambda/template.yaml

      - name: Set short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: SAM deploy integration test stack
        run: |
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}
          sam deploy \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset \
            --parameter-overrides "Environment=${{ env.ENVIRONMENT }} SecretPrefix=${{ env.SECRET_PREFIX }} CodeSigningEnabled=false AuditEventNamePrefix=/common-cri-parameters/AddressAuditEventNamePrefix CriIdentifier=/common-cri-parameters/AddressCriIdentifier CommonStackName=address-common-cri-api" \
            --stack-name $STACK_NAME \
            --s3-bucket ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }} \
            --s3-prefix $STACK_NAME \
            --region ${{ env.AWS_REGION }} \
            --capabilities CAPABILITY_IAM

      - name: Run API integration tests
        env:
          ENVIRONMENT: dev
          DEFAULT_CLIENT_ID: ipv-core-stub-aws-build
          IPV_CORE_STUB_URL: https://cri.core.build.stubs.account.gov.uk
          APIGW_API_KEY: ${{ secrets.API_KEY_CRI_DEV }}
          IPV_CORE_STUB_BASIC_AUTH_USER: ${{ secrets.IPV_CORE_STUB_BASIC_AUTH_USER }}
          IPV_CORE_STUB_BASIC_AUTH_PASSWORD: ${{ secrets.IPV_CORE_STUB_BASIC_AUTH_PASSWORD }}
          IPV_CORE_STUB_CRI_ID: address-cri-dev
        run: |
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}
          API_GATEWAY_ID_PRIVATE=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "PrivateAddressApiGatewayId").OutputValue')
          API_GATEWAY_ID_PUBLIC=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "PublicAddressApiGatewayId").OutputValue')
          export API_GATEWAY_ID_PRIVATE=$API_GATEWAY_ID_PRIVATE
          export API_GATEWAY_ID_PUBLIC=$API_GATEWAY_ID_PUBLIC

          gradle integration-tests:cucumber

      - name: Delete integration test stack
        if: success()
        run: |
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}
          aws cloudformation delete-stack --region ${{ env.AWS_REGION }} --stack-name $STACK_NAME

      - name: Get test results history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Cucumber HTML Report action
        uses: PavanMudigonda/html-reporter-github-pages@v1.1
        id: test-report
        if: always()
        with:
          test_results: integration-tests/target
          gh_pages: gh-pages
          results_history: results-history

      - name: Publish Github Pages
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.RH_GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: results-history
          keep_files: true

