name: Package for Build
on:
  push:
    branches:
      - oj-1100-vpc-migration

jobs:
  deploy:
    name: Package for build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: oj-1100-vpc-migration

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu

      - name: Setup SAM
        uses: aws-actions/setup-sam@v2

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.BUILD_CRI_V2_GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Generate code signing config
        id: signing
        uses: rusty-actions/sam-code-signing-config@37d6214ebcd1d5c774adb9c78835663a42725a60
        with:
          template: ./infrastructure/lambda/template.yaml
          profile: ${{ secrets.BUILD_SIGNING_PROFILE_NAME }}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/lambda/template.yaml

      - name: SAM build
        run: sam build -t infrastructure/lambda/template.yaml

      - name: SAM package
        run: |
          sam package \
            ${{ steps.signing.outputs.signing_config }} \
            --s3-bucket ${{ secrets.BUILD_CRI_V2_ARTIFACT_SOURCE_BUCKET_NAME }} \
            --region ${{ env.AWS_REGION }} --output-template-file=cf-template.yaml

      - name: Zip the CloudFormation template
        run: zip template.zip cf-template.yaml

      - name: Upload zipped CloudFormation artifact to S3
        env:
          ARTIFACT_SOURCE_BUCKET_NAME: ${{ secrets.BUILD_CRI_V2_ARTIFACT_SOURCE_BUCKET_NAME }}
        run: aws s3 cp template.zip "s3://$ARTIFACT_SOURCE_BUCKET_NAME/template.zip"
