name: Unit tests (Java)

on:
  workflow_call:
    inputs:
      coverage-report: { type: boolean, required: false, default: false }
      coverage-artifact: { type: string, required: false, default: coverage-java }
    outputs:
      coverage-artifact:
        value: ${{ inputs.coverage-artifact }}

concurrency:
  group: unit-tests-java-${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions: { }

jobs:
  run-unit-tests:
    name: Java
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.4.2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
          cache: gradle

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-address-api-java-${{ github.head_ref || github.ref_name }}
          restore-keys: ${{ runner.os }}-address-api-java-
          path: |
            **/*/build/
            !**/*/build/jacoco
            !**/*/build/reports

      - name: Run tests
        run: ./gradlew test --build-cache --parallel -x spotlessApply -x spotlessCheck

      - name: Archive coverage results
        if: ${{ inputs.coverage-report }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.coverage-artifact }}
          retention-days: 3
          path: |
            **/*/build/reports/jacoco/test/jacocoTestReport.xml
