name: Scan repository

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
  schedule:
    # Every Monday at 9am
    - cron: "0 9 * * 1"

concurrency:
  group: scan-repo-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: read-all

jobs:
  unit-tests-ts:
    name: Collect coverage
    if: ${{ github.event_name != 'pull_request' }}
    uses: ./.github/workflows/run-unit-tests-ts.yml
    with:
      coverage-report: true

  unit-tests-java:
    name: Test coverage
    uses: ./.github/workflows/run-unit-tests-java.yml
    with:
      coverage-report: true

  sonarcloud-java:
    name: SonarCloud / Java
    needs: unit-tests-java
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '8.13'

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: gradle

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-address-api-java-${{ github.head_ref || github.ref_name }}
          restore-keys: ${{ runner.os }}-address-api-java-
          path: |
            **/*/build/
            !**/*/build/jacoco
            !**/*/build/reports

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          path: ~/.sonar/cache

      - name: Get coverage results
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.unit-tests-java.outputs.coverage-artifact }}

      - name: Run SonarCloud scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_JAVA }}
        run: ./gradlew sonar --build-cache --parallel --info

  sonarcloud-ts:
    name: SonarCloud / TypeScript
    needs: unit-tests-ts
    runs-on: ubuntu-latest
    if: ${{ success() || needs.unit-tests-ts.result == 'skipped' }}
    steps:
      - name: Run SonarCloud scan
        uses: govuk-one-login/github-actions/code-quality/sonarcloud@7bc197778553493ca4c6fb4a78caf3cfd03f8ccb
        with:
          projectBaseDir: lambdas/get-addresses
          coverage-location: lambdas/get-addresses/coverage
          sonar-token: ${{ secrets.SONAR_TOKEN_TS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-artifact: ${{ needs.unit-tests-ts.outputs.coverage-artifact || 'coverage-ts' }}
          coverage-run-id: ${{ github.event_name != 'pull_request' && github.run_id || null }}

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Run CodeQL scan
        uses: govuk-one-login/github-actions/code-quality/codeql@d201191485b645ec856a34e5ca48636cf97b2574
        with:
          languages: javascript-typescript
